export const CHANCE_CARDS = [
  {
    id: "chance-advance-boardwalk",
    title: "राजमार्गः — Advance to Boardwalk",
    message: "Advance to Boardwalk. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-advance-go",
    title: "आरम्भं गच्छ — Advance to Go",
    message: "Advance to Go and collect 200 points.",
    points: 200,
    effect: "advanceToGo",
  },
  {
    id: "chance-advance-illinois",
    title: "धर्मपथः — Advance to Illinois Avenue",
    message: "Advance to Illinois Avenue. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-advance-st-charles",
    title: "शुभस्थानम् — Advance to St. Charles Place",
    message: "Advance to St. Charles Place. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-nearest-railroad-1",
    title: "रेलयानम् — Nearest Railroad",
    message: "Advance to the nearest Railroad. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-nearest-railroad-2",
    title: "रेलयानम् — Nearest Railroad",
    message: "Advance to the nearest Railroad. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-nearest-utility",
    title: "सेवास्थानम् — Nearest Utility",
    message: "Advance token to nearest Utility. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-bank-dividend",
    title: "कोषलाभः — Bank Dividend",
    message: "The royal treasury pays you a dividend. Collect 50 points.",
    points: 50,
    effect: "money",
  },
  {
    id: "chance-get-out-jail",
    title: "मुक्तिपत्रम् — Get Out of Jail Free",
    message: "Receive a Get Out of Jail Free card. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-go-back-three",
    title: "त्रिपदं प्रतिगच्छ — Go Back 3 Spaces",
    message: "Go back 3 spaces.",
    points: 0,
    effect: "goBack3",
  },
  {
    id: "chance-go-to-jail",
    title: "कारागारं गच्छ — Go to Jail",
    message: "Go directly to Jail. Do not pass Go.",
    points: 0,
    effect: "goToJail",
  },
  {
    id: "chance-general-repairs",
    title: "गृहसंस्कारः — General Repairs",
    message: "Make general repairs on all your property. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-speeding-fine",
    title: "अतिवेगदण्डः — Speeding Fine",
    message: "You moved too quickly on the royal road. Pay 15 points.",
    points: -15,
    effect: "money",
  },
  {
    id: "chance-reading-railroad",
    title: "यात्रा — Reading Railroad",
    message: "Take a trip to Reading Railroad. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-chairman-board",
    title: "सभापतिः — Chairman of the Board",
    message: "You have been elected Chairman of the Board. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chance-building-loan",
    title: "ऋणसमाप्तिः — Building Loan Matures",
    message: "Your building loan matures. Collect 150 points.",
    points: 150,
    effect: "money",
  },
];

export const COMMUNITY_CHEST_CARDS = [
  {
    id: "chest-advance-go",
    title: "आरम्भं गच्छ — Advance to Go",
    message: "Advance to Go and collect 200 points.",
    points: 200,
    effect: "advanceToGo",
  },
  {
    id: "chest-bank-error",
    title: "दैवलाभः — Bank Error",
    message: "Bank error in your favor. Collect 200 points.",
    points: 200,
    effect: "money",
  },
  {
    id: "chest-doctors-fee",
    title: "वैद्यशुल्कम् — Doctor’s Fee",
    message: "Pay the healer’s fee. Lose 50 points.",
    points: -50,
    effect: "money",
  },
  {
    id: "chest-stock-sale",
    title: "वाणिज्यलाभः — Sale of Stock",
    message: "From sale of stock, collect 50 points.",
    points: 50,
    effect: "money",
  },
  {
    id: "chest-get-out-jail",
    title: "मुक्तिपत्रम् — Get Out of Jail Free",
    message: "Receive a Get Out of Jail Free card. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chest-go-to-jail",
    title: "कारागारं गच्छ — Go to Jail",
    message: "Go directly to Jail. Do not pass Go.",
    points: 0,
    effect: "goToJail",
  },
  {
    id: "chest-holiday-fund",
    title: "उत्सवनिधिः — Holiday Fund",
    message: "Holiday fund matures. Receive 100 points.",
    points: 100,
    effect: "money",
  },
  {
    id: "chest-tax-refund",
    title: "करप्रतिदानम् — Tax Refund",
    message: "Income tax refund. Collect 20 points.",
    points: 20,
    effect: "money",
  },
  {
    id: "chest-birthday",
    title: "जन्मदिनम् — Birthday",
    message: "It is your birthday. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chest-life-insurance",
    title: "जीवनबीमा — Life Insurance",
    message: "Life insurance matures. Collect 100 points.",
    points: 100,
    effect: "money",
  },
  {
    id: "chest-hospital-fees",
    title: "आरोग्यशुल्कम् — Hospital Fees",
    message: "Pay hospital fees. Lose 100 points.",
    points: -100,
    effect: "money",
  },
  {
    id: "chest-school-fees",
    title: "विद्यालयशुल्कम् — School Fees",
    message: "Pay school fees. Lose 50 points.",
    points: -50,
    effect: "money",
  },
  {
    id: "chest-consultancy-fee",
    title: "मन्त्रणाशुल्कम् — Consultancy Fee",
    message: "Receive 25 points consultancy fee.",
    points: 25,
    effect: "money",
  },
  {
    id: "chest-street-repair",
    title: "मार्गसंस्कारः — Street Repair",
    message: "You are assessed for street repair. This effect will be added later.",
    points: 0,
    effect: "none",
  },
  {
    id: "chest-beauty-contest",
    title: "द्वितीयपुरस्कारः — Beauty Contest",
    message: "You won second prize in a beauty contest. Collect 10 points.",
    points: 10,
    effect: "money",
  },
  {
    id: "chest-inheritance",
    title: "उत्तराधिकारः — Inheritance",
    message: "You inherit 100 points.",
    points: 100,
    effect: "money",
  },
];